### ISSUE TITLE
k8s_api_client.cc: Exception while waiting for pod list: not an object

### ISSUE THREAD

**Issue by xiechengsheng** [camsas/poseidon#3]
Hello, I pulled your camsas/poseidon:dev docker image and wanted to have a try, I used the follow command:
```
$ docker run camsas/poseidon:dev /usr/bin/poseidon \
    --logtostderr \
    --k8s_apiserver_host=192.168.3.89 \
    --k8s_apiserver_port=8080 \
    --cs2_binary=/usr/bin/cs2.exe \
    --max_tasks_per_pu=50
```

But then an exception occurred, here were the logs:
```
I0521 05:59:45.096031     1 scheduler_bridge.cc:44] Firmament scheduler instantiated: 0x1b56650
I0521 05:59:45.096866     1 k8s_api_client.cc:63] Starting K8sApiClient for API server at http://192.168.3.89:8080/
I0521 05:59:45.187544     1 scheduler_bridge.cc:86] Adding new node's resource with RID f4673222-7577-ed4f-a0ec-d5a5c1da1c5d
E0521 05:59:45.262907     1 k8s_api_client.cc:313] Exception while waiting for pod list: not an object
...
```

And here are my pods in my k8s cluster:
```
$ kubectl get pod 
NAME                      READY     STATUS    RESTARTS   AGE
frontend-0d71m            1/1       Running   0          12d
frontend-75xjr            1/1       Running   0          12d
frontend-b54c8            1/1       Running   0          12d
redis-master-3wtcq        1/1       Running   0          12d
redis-slave-3fctv         1/1       Running   0          12d
redis-slave-gm9kk         1/1       Running   0          12d
```

And I looked into the poseidon's source code, it seemed that the APIClient couldn't get the cluster's pods:
[Poll pods](https://github.com/camsas/poseidon/blob/d47fb8ed69762d0d9fc8ae437299f925fcdd357e/src/firmament/scheduler_integration.cc#L63)
And, my OS is CentOS7.2, not the suggested OS Ubuntu14.04... Does this matter?
So what should I do to slove this problem?
Thanks~

**Comment by ICGog** [comment]
The Docker image was several months out of date. Since then we've re-implemented Poseidon in Go. Can you please follow the new instructions to deploy [Poseidon](https://github.com/camsas/poseidon/#getting-started) and [Firmament](https://github.com/camsas/firmament/blob/master/README.md#running-the-firmament-scheduler-service)?

**Comment by xiechengsheng** [comment]
1. Thanks for reply. Yes, I have done this~ 
2. But I don't kown how to configure some startup parameters in the new instructions. I have read the [firmament_scheduler.cfg](https://github.com/camsas/firmament/blob/master/config/firmament_scheduler.cfg) file in firmament, but it seems that the parameter `--firmamentAddress=<host>:<port>` has been configured in the startup parameter `--kubeConfig=<path_kubeconfig_file>`... Is my thought true? What does this two startup parameters mean?
3. And deos the parameter `--statsServerAddress=<host>:<port>` mean the APIServer address?
4. If you can write a brief description or make a short demo video in the README file, that would be wonderful~
5. Looking forward to your reply~

**Comment by ms705** [comment]
@xiechengsheng 

The `--kubeConfig` parameter is not the same as `--firmamentAddress`. `kubeConfig` points to the Kubernetes configuration file (`kubeconfig.cfg`) for your cluster, while `firmamentAddress` is the host-port combination of the Firmament gRPC scheduler service (the `firmament_scheduler` binary, likely running in the Firmament docker container).

`statsServerAddress`, I think, refers to the address of a Poseidon heapster sink to which statistics are delivered. @ICGog should be able to confirm this.

**Comment by xiechengsheng** [comment]
@ms705 Thanks, I will try to run it again and read the source code to know more about Poseidon.

**Comment by ICGog** [comment]
@xiechengsheng @ms705 `statsServerAddress` is the address on which Poseidon listens for statistics sent by our Poseidon Heapster sink (currently under implementation in [https://github.com/camsas/heapster](url)).

**Comment by ms705** [comment]
Closing this; reopen if there are remaining questions.
