### ISSUE TITLE
Firmament scheduler throws error when run with 1.7 kubernetes

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [camsas/poseidon#5]
I am facing a strange issue when using firmament container.

Observations:
Kubernetes version :  1.7

Firmament created using:
```
docker run  --net=host  camsas/firmament:dev /firmament/build/src/firmament_scheduler --flagfile=/firmament/default.conf 
```
Poseidon able to connect to firmament and kubernetes.

Poseidon created using:
```
./poseidon --logtostderr --kubeConfig=<kubeconfig.cfg> --firmamentAddress=localhost:9090.
```
In standard out, I am able to see that both nodes and pods are being successfully watched and task is being submitted to firmament scheduler:

```
I0903 22:37:33.695642   20401 nodewatcher.go:132] enqueueNodeAdition: Added node sample-node-2gjww

I0903 22:37:33.700437   20401 podwatcher.go:176] enqueuePodAddition: Added pod {podname4 test}
I0903 22:37:33.701334   20401 podwatcher.go:176] enqueuePodAddition: Added pod {podname5 test}
```

In firmament stdout, I see this error:
```
I0904 02:37:42.510321    13 utils.cc:341] External execution of command: build/third_party/flowlessly/src/flowlessly-build/flow_scheduler --graph_has_node_types=true --algorithm=successive_shortest_path --print_assignments=true --daemon=false caling_factor= 
W0904 02:37:42.510821    15 solver_dispatcher.cc:143] STDERR from solver: E0904 02:37:42.510514    14 utils.cc:381] execvp failed for task command 'build/third_party/flowlessly/src/flowlessly-build/flow_scheduler --graph_has_node_types=true --algorithm=successive_shortest_path --print_assignments=true --daemon=false caling_factor= ': No such file or directory [2]
```
Result:
Pods are not being scheduled at all.

Just wanted to know, if I missed anything

**Comment by ms705** [comment]
Hi @ravisantoshgudimetla,

This is odd -- the Docker image has worked fine for us in the past. @ICGog says he'll look into this; I may have time to have a look this weekend if it's not been resolved by then.

**Comment by ICGog** [comment]
Hi @ravisantoshgudimetla,

Firmament is crashing because the path to the Flowlessly binary is relative to the directory from which you're running firmament. In your case you're running from /, which means that you should pass `--flow_scheduling_binary=/firmament/build/third_party/flowlessly/src/flowlessly-build/flow_scheduler` instead of `--flow_scheduling_binary=/build/third_party/flowlessly/src/flowlessly-build/flow_scheduler` which is set in default.conf.

**Comment by ravisantoshgudimetla** [comment]
Thanks @ms705 @ICGog. It worked with by passing the `--flow_scheduling_binary` flag. I am closing this issue.
